version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: jenkins/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: jenkins/scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: jenkins/scripts/deliver.sh
      timeout: 300
      runas: ubuntu

